# -*- coding: utf-8 -*-
"""pair trade paylaşım

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5AN_l7Zc-o0Nil14P5k9eneMasfM1qe
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

st.markdown("<h1 style='text-align: center; color: #4CAF50;'>Pair-Trade Arayüzü</h1>", unsafe_allow_html=True)
st.write("---")

col1, col2 = st.columns(2)

with col1:
    initial_capital = st.number_input("Başlangıç Sermayesi (TL)", value=100000)
    commission_rate = st.number_input("Komisyon Oranı (Toplam Long+Short)", value=0.0003, format="%.5f")
    stop_loss = st.number_input("Stop-Loss Seviyesi (%)", value=-0.08, format="%.5f")

with col2:
    min_spread = st.number_input("Minimum Fark (%)", value=0.0006, format="%.5f")
    start_date = st.date_input("Başlangıç Tarihi", value=datetime.today() - timedelta(days=400))
    end_date = st.date_input("Bitiş Tarihi", value=datetime.today())

if st.button("Stratejiyi Çalıştır"):
    tickers = ["GARAN.IS", "ISCTR.IS"]

    df_daily = yf.download(
        tickers,
        start=start_date.strftime("%Y-%m-%d"),
        end=end_date.strftime("%Y-%m-%d"),
        interval="1d",
        auto_adjust=True,
        progress=False
    )
    weekly_close = df_daily["Close"].resample("W-FRI").last().dropna()

    df_hourly = yf.download(
        tickers,
        start=start_date.strftime("%Y-%m-%d"),
        end=end_date.strftime("%Y-%m-%d"),
        interval="1h",
        auto_adjust=True,
        progress=False
    )

    if df_hourly.index.tz is None:
        df_hourly.index = df_hourly.index.tz_localize('UTC')
    df_hourly.index = df_hourly.index.tz_convert('Europe/Istanbul').tz_localize(None)

    current_capital = initial_capital
    equity_rets = []
    timestamps = []
    transactions = []
    stops = []

    mondays = [weekly_close.index[i-1] + timedelta(days=3) for i in range(1, len(weekly_close))]

    for i, monday in enumerate(mondays, start=1):
        prev_fri = weekly_close.index[i-1]
        weekly_up_to = weekly_close.loc[:prev_fri]
        beta = sm.OLS(
            weekly_up_to["GARAN.IS"],
            sm.add_constant(weekly_up_to["ISCTR.IS"])
        ).fit().params["ISCTR.IS"]

        w_long = 1 / (1 + beta)
        w_short = beta / (1 + beta)
        stopped_sides = set()

        next_monday = monday + timedelta(days=7)
        idx0 = df_hourly.index.get_indexer([monday], method='bfill')[0]
        idx1 = df_hourly.index.get_indexer([next_monday], method='bfill')[0]
        week_slice = df_hourly.iloc[idx0:idx1]
        if week_slice.empty:
            continue

        price_ref = week_slice["Close"].iloc[0]
        current_signal = None
        entry_price = None
        entry_cap = None

        for ts, price_ts in week_slice.iloc[1:].iterrows():
            cum = price_ts["Close"] / price_ref - 1
            diff = abs(cum["GARAN.IS"] - cum["ISCTR.IS"])

            if diff < min_spread:
                continue

            new_signal = "GARAN.IS" if cum["GARAN.IS"] < cum["ISCTR.IS"] else "ISCTR.IS"

            if current_signal is None:
                if new_signal in stopped_sides:
                    continue
                current_signal = new_signal
                entry_price = price_ts["Close"].copy()
                entry_cap = current_capital
                continue

            if new_signal != current_signal:
                long_a = current_signal
                short_a = 'ISCTR.IS' if long_a == 'GARAN.IS' else 'GARAN.IS'
                price_start = entry_price
                price_end = price_ts["Close"]

                low_long = price_ts["Low"][long_a]
                high_short = price_ts["High"][short_a]

                stop_long = (low_long / price_start[long_a]) - 1
                stop_short = (price_start[short_a] - high_short) / price_start[short_a]

                ret_long = (price_end[long_a] / price_start[long_a]) - 1
                ret_short = (price_start[short_a] - price_end[short_a]) / price_start[short_a]

                raw_ret = w_long * ret_long + w_short * ret_short
                net_ret = raw_ret - commission_rate
                stop_triggered = False

                if stop_long <= stop_loss or stop_short <= stop_loss:
                    net_ret = stop_loss
                    stop_triggered = True
                    stopped_sides.add(current_signal)
                    stops.append(ts)

                pnl_tl = entry_cap * net_ret

                transactions.append({
                    "Açılış Tarihi": price_start.name,
                    "Kapanış Tarihi": price_end.name,
                    "Pozisyon": f"{long_a} long / {short_a} short",
                    "Kapanış P&L (%)": net_ret * 100,
                    "Kapanış P&L (TL)": pnl_tl,
                    "Stop Oldu mu?": "Evet" if stop_triggered else "Hayır"
                })

                current_capital = entry_cap + pnl_tl
                equity_rets.append(net_ret)
                timestamps.append(ts)

                if new_signal in stopped_sides:
                    current_signal = None
                    continue

                if diff < min_spread:
                    current_signal = None
                    continue

                current_signal = new_signal
                entry_price = price_ts["Close"].copy()
                entry_cap = current_capital

    equity = (1 + pd.Series(equity_rets, index=timestamps)).cumprod() * initial_capital
    final_cap = equity.iloc[-1] if not equity.empty else current_capital

    st.success(f"📈 Final Ana Para: {final_cap:,.2f} TL")

    st.subheader("📊 Performans Özeti")
    if transactions:
        df_trades = pd.DataFrame(transactions)
        total_trades = len(df_trades)
        success_trades = df_trades[df_trades["Kapanış P&L (%)"] > 0].shape[0]
        success_rate = success_trades / total_trades * 100 if total_trades > 0 else 0
        avg_gain = df_trades[df_trades["Kapanış P&L (%)"] > 0]["Kapanış P&L (%)"].mean()
        avg_loss = df_trades[df_trades["Kapanış P&L (%)"] <= 0]["Kapanış P&L (%)"].mean()

        col3, col4, col5 = st.columns(3)
        col3.metric("Toplam İşlem", total_trades)
        col4.metric("Başarı Oranı", f"%{success_rate:.2f}")
        col5.metric("Ortalama Kar/Zarar (%)", f"{avg_gain:.2f} / {avg_loss:.2f}")

    st.subheader("📈 Sermaye Eğrisi")
    fig, ax = plt.subplots(figsize=(12,6))
    ax.plot(equity.index, equity.values, label="Sermaye", marker='o')
    if stops:
        stop_equity = equity.loc[stops]
        ax.scatter(stop_equity.index, stop_equity.values, color="red", label="Stop Loss", zorder=5)
    ax.set_xlabel("Tarih")
    ax.set_ylabel("Sermaye (TL)")
    ax.grid(True)
    ax.legend()
    st.pyplot(fig)

    st.subheader("📋 İşlem Geçmişi")
    df_trades = pd.DataFrame(transactions)
    st.dataframe(df_trades)

    st.subheader("📈 PnL Özeti")
    pnl_df = df_trades[["Kapanış P&L (%)", "Kapanış P&L (TL)"]]
    st.dataframe(pnl_df.style.format({"Kapanış P&L (%)": "{:.2f}%", "Kapanış P&L (TL)": "₺{:.2f}"}))
